name: Cloudflare

on:
  push:
    branches: [master,main]
      
jobs:

  cfclearcache:
    name: Clear cloudflare cache
    runs-on: ubuntu-latest
    steps:
    -
      name: Purge cache for ironpeak.be
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: 'd4577cc5a0f32189d84c5c7fdfd044f0'
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        
    -
      name: Purge cache for ironpeak.services
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: '81314d32814812bcba7b800f8f07a590'
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
