name: Image Optimisation

on:
  push:
    branches: [master,main]

jobs:
  build:
    name: Optimize images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    -
      uses: 9sako6/imgcmp@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
